# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_magnitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('multi_star_hyg_id', models.CharField(blank=True, max_length=8, null=True)),
                ('bayer', models.CharField(blank=True, default='', max_length=8)),
                ('bayer_flamsteed_designation', models.CharField(blank=True, default='', max_length=12)),
                ('color_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('companion_star_hyg_id', models.PositiveIntegerField(blank=True, null=True)),
                ('companion_primary_star_hyg_id', models.PositiveIntegerField(blank=True, null=True)),
                ('constellation_abbreviation', models.CharField(blank=True, default='', max_length=3)),
                ('declination', models.DecimalField(decimal_places=6, max_digits=8)),
                ('declination_rad', models.DecimalField(decimal_places=15, max_digits=16)),
                ('distance_pc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('flamsteed_number', models.CharField(blank=True, default='', max_length=3)),
                ('gliese_id', models.CharField(blank=True, default='', max_length=9)),
                ('henry_draper_id', models.CharField(blank=True, default='', max_length=6)),
                ('hyg_id', models.PositiveIntegerField(blank=True, null=True)),
                ('luminosity', models.FloatField()),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proper_motion_declination', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proper_motion_declination_rad', models.FloatField(null=True)),
                ('proper_motion_right_ascention', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proper_motion_right_ascention_rad', models.FloatField(null=True)),
                ('proper_name', models.CharField(blank=True, default='', max_length=24)),
                ('right_ascention', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('right_ascention_rad', models.FloatField()),
                ('radial_velocity', models.DecimalField(blank=True, decimal_places=1, max_digits=4)),
                ('spectral_type', models.CharField(blank=True, default='', max_length=12)),
                ('variable_star_designation', models.CharField(blank=True, default='', max_length=5)),
                ('variable_max_magnitude', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('variable_min_magnitude', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('velocity_x', models.DecimalField(decimal_places=8, max_digits=12)),
                ('velocity_y', models.DecimalField(decimal_places=8, max_digits=12)),
                ('velocity_z', models.DecimalField(decimal_places=8, max_digits=12)),
                ('x', models.DecimalField(decimal_places=6, max_digits=12)),
                ('y', models.DecimalField(decimal_places=6, max_digits=12)),
                ('z', models.DecimalField(decimal_places=6, max_digits=12)),
                ('constellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constellations.Constellation')),
            ],
        ),
    ]
